dist: xenial

language: node_js
node_js:
  - node # latest stable Node.js release

script:
  - make build

deploy:
  provider: s3
  bucket: familienradwege
  region: eu-central-1
  local_dir: website
  acl: public_read
  skip_cleanup: true
  on: master
