name: build-page

on:
  pull_request:

  push:
    branches:
      - master

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: public
