name: build-page

on: [push]

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install pandoc
      run: brew install pandoc
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci
    - name: Build website
      run: make build
    - uses: actions/upload-artifact@v2
      with:
        name: website
        path: website

  check:
    needs: build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Download website artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: website
        path: website
    - name: Install libxml2
      run: brew install libxml2
    - name: Debug gem env
      run: gem env
    - name: Install html-proofer
      env:
        NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      run: gem install pkg-config:'~> 1.4' html-proofer
    - name: Check website
      run: htmlproofer --empty-alt-ignore website
