name: build-page

on: [push, pull_request]

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install pandoc
      run: brew install pandoc
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci
    - name: Build website
      run: make build
    - uses: actions/upload-artifact@v2
      with:
        name: website
        path: website

  check:
    needs: build
    runs-on: ubuntu-20.04
    container:
      image: jekyll/builder:latest
      volumes:
        - website:/srv/jekyll

    steps:
    - uses: actions/checkout@v2
    - name: Download website artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: website
        path: website
    - name: Check website
      run: /usr/gem/bin/htmlproofer --empty-alt-ignore
